name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main # 当推送到 main 分支时触发
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: lanzou-proxy-app # 你的Cloudflare Pages项目名称
          directory: public # 这是关键，指定你的静态文件目录
          # 如果你的网站不需要构建过程 (纯HTML/CSS/JS)，构建命令可以留空
          # buildCommand: ''
          # 如果有构建命令，比如是 Vue/React 项目，输出目录是 dist，这里就填 dist
